#!/usr/bin/env bash
set -euo pipefail

show_help() {
  cat <<'HELP'
Usage:
  ./ShellScripts/clean-jellyfin-artefacts.sh [--dry-run] [--force-root] "/path/to/media/root"
  ./ShellScripts/clean-jellyfin-artefacts.sh --apply [--force-root] "/path/to/media/root"
  ./ShellScripts/clean-jellyfin-artefacts.sh --help

What this script does:
  - Recursively finds known Jellyfin artefact folders and either previews or removes them.
  - Default mode is --dry-run (preview only).
  - Removal requires --apply.

Safety:
  - Only folders with allowlisted names are targeted.
  - Media files are never selected directly.
  - Root-like dangerous paths (/, /Volumes, /Users, /System, /Applications, /Library) are blocked
    unless you explicitly pass --force-root.

Drag-and-drop example (dry-run):
  ./ShellScripts/clean-jellyfin-artefacts.sh "/Volumes/ExternalDisk/Media"

Delete example (apply):
  ./ShellScripts/clean-jellyfin-artefacts.sh --apply "/Volumes/ExternalDisk/Media"
HELP
}

error_exit() {
  printf 'Error: %s\n' "$1" >&2
  exit 1
}

normalize_escaped_path() {
  local raw_path="$1"
  local normalized_path
  # Finder/Terminal sometimes produce escaped paths (for example: /Volumes/My\ Disk/Folder\ Name).
  # If users wrap that escaped path in quotes, backslashes become literal characters.
  # This converts common escaped path forms back to normal path characters.
  normalized_path="$(printf '%s' "$raw_path" | sed -E 's/\\(.)/\1/g')"
  printf '%s\n' "$normalized_path"
}

human_kib() {
  local kib="$1"
  awk -v kib="$kib" '
    BEGIN {
      units[0] = "KiB"
      units[1] = "MiB"
      units[2] = "GiB"
      units[3] = "TiB"
      value = kib + 0
      unit = 0
      while (value >= 1024 && unit < 3) {
        value = value / 1024
        unit++
      }
      printf "%.2f %s", value, units[unit]
    }
  '
}

is_forbidden_root() {
  local path="$1"
  case "$path" in
    "/"|"/Volumes"|"/Users"|"/System"|"/Applications"|"/Library")
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

mode="dry-run"
force_root="false"
root_path=""

while (($# > 0)); do
  case "$1" in
    --dry-run)
      mode="dry-run"
      shift
      ;;
    --apply)
      mode="apply"
      shift
      ;;
    --force-root)
      force_root="true"
      shift
      ;;
    -h|--help)
      show_help
      exit 0
      ;;
    --)
      shift
      break
      ;;
    -*)
      error_exit "Unknown option: $1. Use --help for usage."
      ;;
    *)
      if [[ -n "$root_path" ]]; then
        error_exit "Only one folder argument is supported. Wrap drag-and-drop paths in quotes if needed."
      fi
      root_path="$1"
      shift
      ;;
  esac
done

if [[ -z "$root_path" && $# -gt 0 ]]; then
  root_path="$1"
  shift
fi

if [[ $# -gt 0 ]]; then
  error_exit "Too many arguments. Use --help for usage examples."
fi

if [[ -z "$root_path" ]]; then
  error_exit "Missing folder argument. Drag a folder into Terminal after the script command."
fi

if [[ ! -e "$root_path" ]]; then
  normalized_candidate="$(normalize_escaped_path "$root_path")"
  if [[ "$normalized_candidate" != "$root_path" && -e "$normalized_candidate" ]]; then
    root_path="$normalized_candidate"
  else
    error_exit "Folder does not exist: $root_path"
  fi
fi

if [[ ! -d "$root_path" ]]; then
  error_exit "Path is not a folder: $root_path"
fi

resolved_root="$(cd "$root_path" && pwd -P)"

if is_forbidden_root "$resolved_root" && [[ "$force_root" != "true" ]]; then
  error_exit "Refusing dangerous root path: $resolved_root. Use --force-root only if you are absolutely sure."
fi

# Known Jellyfin artefact folder patterns that can be safely regenerated by Jellyfin.
# We support both hidden folder names (for example: .trickplay) and suffix-based names
# (for example: Some Episode.trickplay).
declare -a matches=()
is_allowlisted_name() {
  local candidate="$1"
  case "$candidate" in
    ".trickplay"|*.trickplay)
      return 0
      ;;
    ".actors"|*.actors)
      return 0
      ;;
    ".theme-music"|*.theme-music)
      return 0
      ;;
    ".theme-videos"|*.theme-videos)
      return 0
      ;;
    "extrafanart")
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

while IFS= read -r -d '' dir_path; do
  base_name="$(basename "$dir_path")"
  if is_allowlisted_name "$base_name"; then
    matches+=("$dir_path")
  fi
done < <(find "$resolved_root" -type d -print0 2>/dev/null)

if ((${#matches[@]} == 0)); then
  printf 'No allowlisted Jellyfin artefact folders found under: %s\n' "$resolved_root"
  printf 'No media files were targeted.\n'
  exit 0
fi

total_kib=0
for dir_path in "${matches[@]}"; do
  # du -sk reports size in KiB and handles nested contents.
  size_kib="$(du -sk "$dir_path" 2>/dev/null | awk '{print $1}')"
  size_kib="${size_kib:-0}"
  total_kib=$((total_kib + size_kib))
done

printf 'Mode: %s\n' "$mode"
printf 'Root: %s\n' "$resolved_root"
printf 'Allowlisted artefact folders found: %d\n' "${#matches[@]}"
printf 'Estimated total size: %s\n' "$(human_kib "$total_kib")"
printf '\n'

for dir_path in "${matches[@]}"; do
  size_kib="$(du -sk "$dir_path" 2>/dev/null | awk '{print $1}')"
  size_kib="${size_kib:-0}"
  printf '%s  (%s)\n' "$dir_path" "$(human_kib "$size_kib")"
done

printf '\n'

deleted_count=0
skipped_count=0

if [[ "$mode" == "dry-run" ]]; then
  skipped_count="${#matches[@]}"
  printf 'Dry-run complete. Pass --apply to remove the listed folders.\n'
else
  for dir_path in "${matches[@]}"; do
    if [[ -d "$dir_path" ]]; then
      rm -rf -- "$dir_path"
      deleted_count=$((deleted_count + 1))
    else
      skipped_count=$((skipped_count + 1))
    fi
  done
  printf 'Deletion complete.\n'
fi

printf '\nSummary:\n'
printf '  Found: %d\n' "${#matches[@]}"
printf '  Deleted: %d\n' "$deleted_count"
printf '  Skipped: %d\n' "$skipped_count"
printf 'No media files were targeted.\n'
